/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/contact_header.glb --transform 
Files: ./public/contact_header.glb [994.13KB] > /Users/slim-cd/Documents/_Projects/__Creative Directors Website/website 2025/Contact_page/contact_header-transformed.glb [74.23KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ContactHeader(props) {
  const { nodes, materials } = useGLTF('models/contact_header-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bevel.geometry} material={materials['Material.001']} position={[4.458, 0.034, -0.398]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Text_projekte.geometry} material={materials.White} position={[4.458, 0.034, -0.278]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/contact_header-transformed.glb')
